name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Hugging Face
        uses: Hugging Face/action-hub-docker-login@v1
        with:
          hf-api-token: ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Build and Push to Hugging Face Spaces
        uses: Hugging Face/action-hub-push@v1
        with:
          hf-api-token: ${{ secrets.HUGGINGFACE_TOKEN }}
          dockerfile: Dockerfile
          context: ./
